// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbg_nodes.proto

#ifndef PROTOBUF_nbg_5fnodes_2eproto__INCLUDED
#define PROTOBUF_nbg_5fnodes_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_nbg_5fnodes_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsCoordinatesImpl();
void InitDefaultsCoordinates();
void InitDefaultsMLDNBGImpl();
void InitDefaultsMLDNBG();
inline void InitDefaults() {
  InitDefaultsCoordinates();
  InitDefaultsMLDNBG();
}
}  // namespace protobuf_nbg_5fnodes_2eproto
namespace pbmldnbg {
class Coordinates;
class CoordinatesDefaultTypeInternal;
extern CoordinatesDefaultTypeInternal _Coordinates_default_instance_;
class MLDNBG;
class MLDNBGDefaultTypeInternal;
extern MLDNBGDefaultTypeInternal _MLDNBG_default_instance_;
}  // namespace pbmldnbg
namespace pbmldnbg {

// ===================================================================

class Coordinates : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmldnbg.Coordinates) */ {
 public:
  Coordinates();
  virtual ~Coordinates();

  Coordinates(const Coordinates& from);

  inline Coordinates& operator=(const Coordinates& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Coordinates(Coordinates&& from) noexcept
    : Coordinates() {
    *this = ::std::move(from);
  }

  inline Coordinates& operator=(Coordinates&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Coordinates& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Coordinates* internal_default_instance() {
    return reinterpret_cast<const Coordinates*>(
               &_Coordinates_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Coordinates* other);
  friend void swap(Coordinates& a, Coordinates& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Coordinates* New() const PROTOBUF_FINAL { return New(NULL); }

  Coordinates* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Coordinates& from);
  void MergeFrom(const Coordinates& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Coordinates* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double lon = 1;
  bool has_lon() const;
  void clear_lon();
  static const int kLonFieldNumber = 1;
  double lon() const;
  void set_lon(double value);

  // optional double lat = 2;
  bool has_lat() const;
  void clear_lat();
  static const int kLatFieldNumber = 2;
  double lat() const;
  void set_lat(double value);

  // @@protoc_insertion_point(class_scope:pbmldnbg.Coordinates)
 private:
  void set_has_lon();
  void clear_has_lon();
  void set_has_lat();
  void clear_has_lat();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double lon_;
  double lat_;
  friend struct ::protobuf_nbg_5fnodes_2eproto::TableStruct;
  friend void ::protobuf_nbg_5fnodes_2eproto::InitDefaultsCoordinatesImpl();
};
// -------------------------------------------------------------------

class MLDNBG : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbmldnbg.MLDNBG) */ {
 public:
  MLDNBG();
  virtual ~MLDNBG();

  MLDNBG(const MLDNBG& from);

  inline MLDNBG& operator=(const MLDNBG& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MLDNBG(MLDNBG&& from) noexcept
    : MLDNBG() {
    *this = ::std::move(from);
  }

  inline MLDNBG& operator=(MLDNBG&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MLDNBG& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MLDNBG* internal_default_instance() {
    return reinterpret_cast<const MLDNBG*>(
               &_MLDNBG_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(MLDNBG* other);
  friend void swap(MLDNBG& a, MLDNBG& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MLDNBG* New() const PROTOBUF_FINAL { return New(NULL); }

  MLDNBG* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MLDNBG& from);
  void MergeFrom(const MLDNBG& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MLDNBG* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .pbmldnbg.Coordinates coord = 1;
  int coord_size() const;
  void clear_coord();
  static const int kCoordFieldNumber = 1;
  const ::pbmldnbg::Coordinates& coord(int index) const;
  ::pbmldnbg::Coordinates* mutable_coord(int index);
  ::pbmldnbg::Coordinates* add_coord();
  ::google::protobuf::RepeatedPtrField< ::pbmldnbg::Coordinates >*
      mutable_coord();
  const ::google::protobuf::RepeatedPtrField< ::pbmldnbg::Coordinates >&
      coord() const;

  // repeated uint64 osmid = 2;
  int osmid_size() const;
  void clear_osmid();
  static const int kOsmidFieldNumber = 2;
  ::google::protobuf::uint64 osmid(int index) const;
  void set_osmid(int index, ::google::protobuf::uint64 value);
  void add_osmid(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      osmid() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_osmid();

  // @@protoc_insertion_point(class_scope:pbmldnbg.MLDNBG)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::pbmldnbg::Coordinates > coord_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > osmid_;
  friend struct ::protobuf_nbg_5fnodes_2eproto::TableStruct;
  friend void ::protobuf_nbg_5fnodes_2eproto::InitDefaultsMLDNBGImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Coordinates

// optional double lon = 1;
inline bool Coordinates::has_lon() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Coordinates::set_has_lon() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Coordinates::clear_has_lon() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Coordinates::clear_lon() {
  lon_ = 0;
  clear_has_lon();
}
inline double Coordinates::lon() const {
  // @@protoc_insertion_point(field_get:pbmldnbg.Coordinates.lon)
  return lon_;
}
inline void Coordinates::set_lon(double value) {
  set_has_lon();
  lon_ = value;
  // @@protoc_insertion_point(field_set:pbmldnbg.Coordinates.lon)
}

// optional double lat = 2;
inline bool Coordinates::has_lat() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Coordinates::set_has_lat() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Coordinates::clear_has_lat() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Coordinates::clear_lat() {
  lat_ = 0;
  clear_has_lat();
}
inline double Coordinates::lat() const {
  // @@protoc_insertion_point(field_get:pbmldnbg.Coordinates.lat)
  return lat_;
}
inline void Coordinates::set_lat(double value) {
  set_has_lat();
  lat_ = value;
  // @@protoc_insertion_point(field_set:pbmldnbg.Coordinates.lat)
}

// -------------------------------------------------------------------

// MLDNBG

// repeated .pbmldnbg.Coordinates coord = 1;
inline int MLDNBG::coord_size() const {
  return coord_.size();
}
inline void MLDNBG::clear_coord() {
  coord_.Clear();
}
inline const ::pbmldnbg::Coordinates& MLDNBG::coord(int index) const {
  // @@protoc_insertion_point(field_get:pbmldnbg.MLDNBG.coord)
  return coord_.Get(index);
}
inline ::pbmldnbg::Coordinates* MLDNBG::mutable_coord(int index) {
  // @@protoc_insertion_point(field_mutable:pbmldnbg.MLDNBG.coord)
  return coord_.Mutable(index);
}
inline ::pbmldnbg::Coordinates* MLDNBG::add_coord() {
  // @@protoc_insertion_point(field_add:pbmldnbg.MLDNBG.coord)
  return coord_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::pbmldnbg::Coordinates >*
MLDNBG::mutable_coord() {
  // @@protoc_insertion_point(field_mutable_list:pbmldnbg.MLDNBG.coord)
  return &coord_;
}
inline const ::google::protobuf::RepeatedPtrField< ::pbmldnbg::Coordinates >&
MLDNBG::coord() const {
  // @@protoc_insertion_point(field_list:pbmldnbg.MLDNBG.coord)
  return coord_;
}

// repeated uint64 osmid = 2;
inline int MLDNBG::osmid_size() const {
  return osmid_.size();
}
inline void MLDNBG::clear_osmid() {
  osmid_.Clear();
}
inline ::google::protobuf::uint64 MLDNBG::osmid(int index) const {
  // @@protoc_insertion_point(field_get:pbmldnbg.MLDNBG.osmid)
  return osmid_.Get(index);
}
inline void MLDNBG::set_osmid(int index, ::google::protobuf::uint64 value) {
  osmid_.Set(index, value);
  // @@protoc_insertion_point(field_set:pbmldnbg.MLDNBG.osmid)
}
inline void MLDNBG::add_osmid(::google::protobuf::uint64 value) {
  osmid_.Add(value);
  // @@protoc_insertion_point(field_add:pbmldnbg.MLDNBG.osmid)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
MLDNBG::osmid() const {
  // @@protoc_insertion_point(field_list:pbmldnbg.MLDNBG.osmid)
  return osmid_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
MLDNBG::mutable_osmid() {
  // @@protoc_insertion_point(field_mutable_list:pbmldnbg.MLDNBG.osmid)
  return &osmid_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pbmldnbg

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_nbg_5fnodes_2eproto__INCLUDED
