// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nbg_nodes.proto

#include "nbg_nodes.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace pbmldnbg {
class CoordinatesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Coordinates>
      _instance;
} _Coordinates_default_instance_;
class MLDNBGDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MLDNBG>
      _instance;
} _MLDNBG_default_instance_;
}  // namespace pbmldnbg
namespace protobuf_nbg_5fnodes_2eproto {
void InitDefaultsCoordinatesImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::pbmldnbg::_Coordinates_default_instance_;
    new (ptr) ::pbmldnbg::Coordinates();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pbmldnbg::Coordinates::InitAsDefaultInstance();
}

void InitDefaultsCoordinates() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCoordinatesImpl);
}

void InitDefaultsMLDNBGImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_nbg_5fnodes_2eproto::InitDefaultsCoordinates();
  {
    void* ptr = &::pbmldnbg::_MLDNBG_default_instance_;
    new (ptr) ::pbmldnbg::MLDNBG();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pbmldnbg::MLDNBG::InitAsDefaultInstance();
}

void InitDefaultsMLDNBG() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMLDNBGImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pbmldnbg::Coordinates, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pbmldnbg::Coordinates, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pbmldnbg::Coordinates, lon_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pbmldnbg::Coordinates, lat_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pbmldnbg::MLDNBG, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pbmldnbg::MLDNBG, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pbmldnbg::MLDNBG, coord_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::pbmldnbg::MLDNBG, osmid_),
  ~0u,
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::pbmldnbg::Coordinates)},
  { 9, 16, sizeof(::pbmldnbg::MLDNBG)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::pbmldnbg::_Coordinates_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::pbmldnbg::_MLDNBG_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "nbg_nodes.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017nbg_nodes.proto\022\010pbmldnbg\"\'\n\013Coordinat"
      "es\022\013\n\003lon\030\001 \001(\001\022\013\n\003lat\030\002 \001(\001\"=\n\006MLDNBG\022$"
      "\n\005coord\030\001 \003(\0132\025.pbmldnbg.Coordinates\022\r\n\005"
      "osmid\030\002 \003(\004"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 131);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "nbg_nodes.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_nbg_5fnodes_2eproto
namespace pbmldnbg {

// ===================================================================

void Coordinates::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Coordinates::kLonFieldNumber;
const int Coordinates::kLatFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Coordinates::Coordinates()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_nbg_5fnodes_2eproto::InitDefaultsCoordinates();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbmldnbg.Coordinates)
}
Coordinates::Coordinates(const Coordinates& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&lon_, &from.lon_,
    static_cast<size_t>(reinterpret_cast<char*>(&lat_) -
    reinterpret_cast<char*>(&lon_)) + sizeof(lat_));
  // @@protoc_insertion_point(copy_constructor:pbmldnbg.Coordinates)
}

void Coordinates::SharedCtor() {
  _cached_size_ = 0;
  ::memset(&lon_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&lat_) -
      reinterpret_cast<char*>(&lon_)) + sizeof(lat_));
}

Coordinates::~Coordinates() {
  // @@protoc_insertion_point(destructor:pbmldnbg.Coordinates)
  SharedDtor();
}

void Coordinates::SharedDtor() {
}

void Coordinates::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Coordinates::descriptor() {
  ::protobuf_nbg_5fnodes_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nbg_5fnodes_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Coordinates& Coordinates::default_instance() {
  ::protobuf_nbg_5fnodes_2eproto::InitDefaultsCoordinates();
  return *internal_default_instance();
}

Coordinates* Coordinates::New(::google::protobuf::Arena* arena) const {
  Coordinates* n = new Coordinates;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Coordinates::Clear() {
// @@protoc_insertion_point(message_clear_start:pbmldnbg.Coordinates)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    ::memset(&lon_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&lat_) -
        reinterpret_cast<char*>(&lon_)) + sizeof(lat_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Coordinates::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbmldnbg.Coordinates)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double lon = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {
          set_has_lon();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lon_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double lat = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u /* 17 & 0xFF */)) {
          set_has_lat();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &lat_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbmldnbg.Coordinates)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbmldnbg.Coordinates)
  return false;
#undef DO_
}

void Coordinates::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbmldnbg.Coordinates)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double lon = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->lon(), output);
  }

  // optional double lat = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->lat(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pbmldnbg.Coordinates)
}

::google::protobuf::uint8* Coordinates::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pbmldnbg.Coordinates)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional double lon = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->lon(), target);
  }

  // optional double lat = 2;
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->lat(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbmldnbg.Coordinates)
  return target;
}

size_t Coordinates::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbmldnbg.Coordinates)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional double lon = 1;
    if (has_lon()) {
      total_size += 1 + 8;
    }

    // optional double lat = 2;
    if (has_lat()) {
      total_size += 1 + 8;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Coordinates::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbmldnbg.Coordinates)
  GOOGLE_DCHECK_NE(&from, this);
  const Coordinates* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Coordinates>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbmldnbg.Coordinates)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbmldnbg.Coordinates)
    MergeFrom(*source);
  }
}

void Coordinates::MergeFrom(const Coordinates& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbmldnbg.Coordinates)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      lon_ = from.lon_;
    }
    if (cached_has_bits & 0x00000002u) {
      lat_ = from.lat_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Coordinates::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbmldnbg.Coordinates)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Coordinates::CopyFrom(const Coordinates& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbmldnbg.Coordinates)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Coordinates::IsInitialized() const {
  return true;
}

void Coordinates::Swap(Coordinates* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Coordinates::InternalSwap(Coordinates* other) {
  using std::swap;
  swap(lon_, other->lon_);
  swap(lat_, other->lat_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Coordinates::GetMetadata() const {
  protobuf_nbg_5fnodes_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nbg_5fnodes_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MLDNBG::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MLDNBG::kCoordFieldNumber;
const int MLDNBG::kOsmidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MLDNBG::MLDNBG()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_nbg_5fnodes_2eproto::InitDefaultsMLDNBG();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbmldnbg.MLDNBG)
}
MLDNBG::MLDNBG(const MLDNBG& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      coord_(from.coord_),
      osmid_(from.osmid_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pbmldnbg.MLDNBG)
}

void MLDNBG::SharedCtor() {
  _cached_size_ = 0;
}

MLDNBG::~MLDNBG() {
  // @@protoc_insertion_point(destructor:pbmldnbg.MLDNBG)
  SharedDtor();
}

void MLDNBG::SharedDtor() {
}

void MLDNBG::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MLDNBG::descriptor() {
  ::protobuf_nbg_5fnodes_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nbg_5fnodes_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MLDNBG& MLDNBG::default_instance() {
  ::protobuf_nbg_5fnodes_2eproto::InitDefaultsMLDNBG();
  return *internal_default_instance();
}

MLDNBG* MLDNBG::New(::google::protobuf::Arena* arena) const {
  MLDNBG* n = new MLDNBG;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MLDNBG::Clear() {
// @@protoc_insertion_point(message_clear_start:pbmldnbg.MLDNBG)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  coord_.Clear();
  osmid_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool MLDNBG::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbmldnbg.MLDNBG)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pbmldnbg.Coordinates coord = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_coord()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated uint64 osmid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 1, 16u, input, this->mutable_osmid())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, this->mutable_osmid())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbmldnbg.MLDNBG)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbmldnbg.MLDNBG)
  return false;
#undef DO_
}

void MLDNBG::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbmldnbg.MLDNBG)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pbmldnbg.Coordinates coord = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->coord_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->coord(static_cast<int>(i)), output);
  }

  // repeated uint64 osmid = 2;
  for (int i = 0, n = this->osmid_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(
      2, this->osmid(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pbmldnbg.MLDNBG)
}

::google::protobuf::uint8* MLDNBG::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pbmldnbg.MLDNBG)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .pbmldnbg.Coordinates coord = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->coord_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->coord(static_cast<int>(i)), deterministic, target);
  }

  // repeated uint64 osmid = 2;
  target = ::google::protobuf::internal::WireFormatLite::
    WriteUInt64ToArray(2, this->osmid_, target);

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbmldnbg.MLDNBG)
  return target;
}

size_t MLDNBG::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbmldnbg.MLDNBG)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .pbmldnbg.Coordinates coord = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->coord_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->coord(static_cast<int>(i)));
    }
  }

  // repeated uint64 osmid = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      UInt64Size(this->osmid_);
    total_size += 1 *
                  ::google::protobuf::internal::FromIntSize(this->osmid_size());
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MLDNBG::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbmldnbg.MLDNBG)
  GOOGLE_DCHECK_NE(&from, this);
  const MLDNBG* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MLDNBG>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbmldnbg.MLDNBG)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbmldnbg.MLDNBG)
    MergeFrom(*source);
  }
}

void MLDNBG::MergeFrom(const MLDNBG& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbmldnbg.MLDNBG)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  coord_.MergeFrom(from.coord_);
  osmid_.MergeFrom(from.osmid_);
}

void MLDNBG::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbmldnbg.MLDNBG)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MLDNBG::CopyFrom(const MLDNBG& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbmldnbg.MLDNBG)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MLDNBG::IsInitialized() const {
  return true;
}

void MLDNBG::Swap(MLDNBG* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MLDNBG::InternalSwap(MLDNBG* other) {
  using std::swap;
  coord_.InternalSwap(&other->coord_);
  osmid_.InternalSwap(&other->osmid_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MLDNBG::GetMetadata() const {
  protobuf_nbg_5fnodes_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_nbg_5fnodes_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pbmldnbg

// @@protoc_insertion_point(global_scope)
