// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scc.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "scc.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pbscc {
class EdgesDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Edges>
     _instance;
} _Edges_default_instance_;
class SCCGraphDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SCCGraph>
     _instance;
} _SCCGraph_default_instance_;

namespace protobuf_scc_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Edges, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Edges, targets_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SCCGraph, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SCCGraph, v_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SCCGraph, adj_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(Edges)},
  { 6, -1, sizeof(SCCGraph)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Edges_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_SCCGraph_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "scc.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Edges_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_Edges_default_instance_);_SCCGraph_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_SCCGraph_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\tscc.proto\022\005pbscc\"\030\n\005Edges\022\017\n\007targets\030\003"
      " \003(\005\"0\n\010SCCGraph\022\t\n\001V\030\001 \001(\005\022\031\n\003adj\030\004 \003(\013"
      "2\014.pbscc.Edgesb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 102);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "scc.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_scc_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Edges::kTargetsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Edges::Edges()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_scc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbscc.Edges)
}
Edges::Edges(const Edges& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      targets_(from.targets_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:pbscc.Edges)
}

void Edges::SharedCtor() {
  _cached_size_ = 0;
}

Edges::~Edges() {
  // @@protoc_insertion_point(destructor:pbscc.Edges)
  SharedDtor();
}

void Edges::SharedDtor() {
}

void Edges::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Edges::descriptor() {
  protobuf_scc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_scc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Edges& Edges::default_instance() {
  protobuf_scc_2eproto::InitDefaults();
  return *internal_default_instance();
}

Edges* Edges::New(::google::protobuf::Arena* arena) const {
  Edges* n = new Edges;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Edges::Clear() {
// @@protoc_insertion_point(message_clear_start:pbscc.Edges)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  targets_.Clear();
  _internal_metadata_.Clear();
}

bool Edges::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbscc.Edges)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 targets = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_targets())));
        } else if (
            static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26u, input, this->mutable_targets())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbscc.Edges)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbscc.Edges)
  return false;
#undef DO_
}

void Edges::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbscc.Edges)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 targets = 3;
  if (this->targets_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::google::protobuf::uint32>(
        _targets_cached_byte_size_));
  }
  for (int i = 0, n = this->targets_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->targets(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pbscc.Edges)
}

::google::protobuf::uint8* Edges::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pbscc.Edges)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 targets = 3;
  if (this->targets_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::google::protobuf::uint32>(
            _targets_cached_byte_size_), target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->targets_, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbscc.Edges)
  return target;
}

size_t Edges::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbscc.Edges)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated int32 targets = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->targets_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _targets_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Edges::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbscc.Edges)
  GOOGLE_DCHECK_NE(&from, this);
  const Edges* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Edges>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbscc.Edges)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbscc.Edges)
    MergeFrom(*source);
  }
}

void Edges::MergeFrom(const Edges& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbscc.Edges)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  targets_.MergeFrom(from.targets_);
}

void Edges::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbscc.Edges)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Edges::CopyFrom(const Edges& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbscc.Edges)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Edges::IsInitialized() const {
  return true;
}

void Edges::Swap(Edges* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Edges::InternalSwap(Edges* other) {
  using std::swap;
  targets_.InternalSwap(&other->targets_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Edges::GetMetadata() const {
  protobuf_scc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_scc_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Edges

// repeated int32 targets = 3;
int Edges::targets_size() const {
  return targets_.size();
}
void Edges::clear_targets() {
  targets_.Clear();
}
::google::protobuf::int32 Edges::targets(int index) const {
  // @@protoc_insertion_point(field_get:pbscc.Edges.targets)
  return targets_.Get(index);
}
void Edges::set_targets(int index, ::google::protobuf::int32 value) {
  targets_.Set(index, value);
  // @@protoc_insertion_point(field_set:pbscc.Edges.targets)
}
void Edges::add_targets(::google::protobuf::int32 value) {
  targets_.Add(value);
  // @@protoc_insertion_point(field_add:pbscc.Edges.targets)
}
const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Edges::targets() const {
  // @@protoc_insertion_point(field_list:pbscc.Edges.targets)
  return targets_;
}
::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Edges::mutable_targets() {
  // @@protoc_insertion_point(field_mutable_list:pbscc.Edges.targets)
  return &targets_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SCCGraph::kVFieldNumber;
const int SCCGraph::kAdjFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SCCGraph::SCCGraph()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_scc_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:pbscc.SCCGraph)
}
SCCGraph::SCCGraph(const SCCGraph& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      adj_(from.adj_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  v_ = from.v_;
  // @@protoc_insertion_point(copy_constructor:pbscc.SCCGraph)
}

void SCCGraph::SharedCtor() {
  v_ = 0;
  _cached_size_ = 0;
}

SCCGraph::~SCCGraph() {
  // @@protoc_insertion_point(destructor:pbscc.SCCGraph)
  SharedDtor();
}

void SCCGraph::SharedDtor() {
}

void SCCGraph::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SCCGraph::descriptor() {
  protobuf_scc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_scc_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SCCGraph& SCCGraph::default_instance() {
  protobuf_scc_2eproto::InitDefaults();
  return *internal_default_instance();
}

SCCGraph* SCCGraph::New(::google::protobuf::Arena* arena) const {
  SCCGraph* n = new SCCGraph;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SCCGraph::Clear() {
// @@protoc_insertion_point(message_clear_start:pbscc.SCCGraph)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  adj_.Clear();
  v_ = 0;
  _internal_metadata_.Clear();
}

bool SCCGraph::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pbscc.SCCGraph)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 V = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &v_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pbscc.Edges adj = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_adj()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pbscc.SCCGraph)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pbscc.SCCGraph)
  return false;
#undef DO_
}

void SCCGraph::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pbscc.SCCGraph)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 V = 1;
  if (this->v() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->v(), output);
  }

  // repeated .pbscc.Edges adj = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->adj_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->adj(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:pbscc.SCCGraph)
}

::google::protobuf::uint8* SCCGraph::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:pbscc.SCCGraph)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 V = 1;
  if (this->v() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->v(), target);
  }

  // repeated .pbscc.Edges adj = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->adj_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, this->adj(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pbscc.SCCGraph)
  return target;
}

size_t SCCGraph::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pbscc.SCCGraph)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .pbscc.Edges adj = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->adj_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->adj(static_cast<int>(i)));
    }
  }

  // int32 V = 1;
  if (this->v() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->v());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SCCGraph::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:pbscc.SCCGraph)
  GOOGLE_DCHECK_NE(&from, this);
  const SCCGraph* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SCCGraph>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:pbscc.SCCGraph)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:pbscc.SCCGraph)
    MergeFrom(*source);
  }
}

void SCCGraph::MergeFrom(const SCCGraph& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pbscc.SCCGraph)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  adj_.MergeFrom(from.adj_);
  if (from.v() != 0) {
    set_v(from.v());
  }
}

void SCCGraph::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:pbscc.SCCGraph)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SCCGraph::CopyFrom(const SCCGraph& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pbscc.SCCGraph)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SCCGraph::IsInitialized() const {
  return true;
}

void SCCGraph::Swap(SCCGraph* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SCCGraph::InternalSwap(SCCGraph* other) {
  using std::swap;
  adj_.InternalSwap(&other->adj_);
  swap(v_, other->v_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SCCGraph::GetMetadata() const {
  protobuf_scc_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_scc_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SCCGraph

// int32 V = 1;
void SCCGraph::clear_v() {
  v_ = 0;
}
::google::protobuf::int32 SCCGraph::v() const {
  // @@protoc_insertion_point(field_get:pbscc.SCCGraph.V)
  return v_;
}
void SCCGraph::set_v(::google::protobuf::int32 value) {
  
  v_ = value;
  // @@protoc_insertion_point(field_set:pbscc.SCCGraph.V)
}

// repeated .pbscc.Edges adj = 4;
int SCCGraph::adj_size() const {
  return adj_.size();
}
void SCCGraph::clear_adj() {
  adj_.Clear();
}
const ::pbscc::Edges& SCCGraph::adj(int index) const {
  // @@protoc_insertion_point(field_get:pbscc.SCCGraph.adj)
  return adj_.Get(index);
}
::pbscc::Edges* SCCGraph::mutable_adj(int index) {
  // @@protoc_insertion_point(field_mutable:pbscc.SCCGraph.adj)
  return adj_.Mutable(index);
}
::pbscc::Edges* SCCGraph::add_adj() {
  // @@protoc_insertion_point(field_add:pbscc.SCCGraph.adj)
  return adj_.Add();
}
::google::protobuf::RepeatedPtrField< ::pbscc::Edges >*
SCCGraph::mutable_adj() {
  // @@protoc_insertion_point(field_mutable_list:pbscc.SCCGraph.adj)
  return &adj_;
}
const ::google::protobuf::RepeatedPtrField< ::pbscc::Edges >&
SCCGraph::adj() const {
  // @@protoc_insertion_point(field_list:pbscc.SCCGraph.adj)
  return adj_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pbscc

// @@protoc_insertion_point(global_scope)
