// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: turn-penalty.proto

#ifndef PROTOBUF_turn_2dpenalty_2eproto__INCLUDED
#define PROTOBUF_turn_2dpenalty_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_turn_2dpenalty_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsTurnPenaltyImpl();
void InitDefaultsTurnPenalty();
inline void InitDefaults() {
  InitDefaultsTurnPenalty();
}
}  // namespace protobuf_turn_2dpenalty_2eproto
namespace pbtp {
class TurnPenalty;
class TurnPenaltyDefaultTypeInternal;
extern TurnPenaltyDefaultTypeInternal _TurnPenalty_default_instance_;
}  // namespace pbtp
namespace pbtp {

// ===================================================================

class TurnPenalty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pbtp.TurnPenalty) */ {
 public:
  TurnPenalty();
  virtual ~TurnPenalty();

  TurnPenalty(const TurnPenalty& from);

  inline TurnPenalty& operator=(const TurnPenalty& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TurnPenalty(TurnPenalty&& from) noexcept
    : TurnPenalty() {
    *this = ::std::move(from);
  }

  inline TurnPenalty& operator=(TurnPenalty&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TurnPenalty& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TurnPenalty* internal_default_instance() {
    return reinterpret_cast<const TurnPenalty*>(
               &_TurnPenalty_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(TurnPenalty* other);
  friend void swap(TurnPenalty& a, TurnPenalty& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TurnPenalty* New() const PROTOBUF_FINAL { return New(NULL); }

  TurnPenalty* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const TurnPenalty& from);
  void MergeFrom(const TurnPenalty& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(TurnPenalty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 penalty = 1;
  int penalty_size() const;
  void clear_penalty();
  static const int kPenaltyFieldNumber = 1;
  ::google::protobuf::int32 penalty(int index) const;
  void set_penalty(int index, ::google::protobuf::int32 value);
  void add_penalty(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      penalty() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_penalty();

  // @@protoc_insertion_point(class_scope:pbtp.TurnPenalty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > penalty_;
  friend struct ::protobuf_turn_2dpenalty_2eproto::TableStruct;
  friend void ::protobuf_turn_2dpenalty_2eproto::InitDefaultsTurnPenaltyImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TurnPenalty

// repeated int32 penalty = 1;
inline int TurnPenalty::penalty_size() const {
  return penalty_.size();
}
inline void TurnPenalty::clear_penalty() {
  penalty_.Clear();
}
inline ::google::protobuf::int32 TurnPenalty::penalty(int index) const {
  // @@protoc_insertion_point(field_get:pbtp.TurnPenalty.penalty)
  return penalty_.Get(index);
}
inline void TurnPenalty::set_penalty(int index, ::google::protobuf::int32 value) {
  penalty_.Set(index, value);
  // @@protoc_insertion_point(field_set:pbtp.TurnPenalty.penalty)
}
inline void TurnPenalty::add_penalty(::google::protobuf::int32 value) {
  penalty_.Add(value);
  // @@protoc_insertion_point(field_add:pbtp.TurnPenalty.penalty)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
TurnPenalty::penalty() const {
  // @@protoc_insertion_point(field_list:pbtp.TurnPenalty.penalty)
  return penalty_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
TurnPenalty::mutable_penalty() {
  // @@protoc_insertion_point(field_mutable_list:pbtp.TurnPenalty.penalty)
  return &penalty_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace pbtp

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_turn_2dpenalty_2eproto__INCLUDED
